- name: Deploy to UmbHost
  uses: UmbHost/umbhost-web-deploy-composite-action@1.0.0
    with:
      website-name: ${{ secrets.WEBSITE_NAME }}
      server-computer-name: ${{ secrets.SERVER_COMPUTER_NAME }}
      server-username: ${{ secrets.USERNAME }}
      server-password: ${{ secrets.PASSWORD }}
      source-path: '_build'
      source-paramFile: 'Umbraco.Web.SetParameters.xml'
